# syntax=docker/dockerfile:1
FROM golang:1.24

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
RUN go mod tidy
COPY . .

# Copy .env file if present
COPY .env .env

# Run the bot
CMD ["go", "run", "main.go"]
